### ISSUE TITLE
Compatibility with GeoIPLite2 database

### ISSUE THREAD

**Issue by detj** [runk/node-maxmind#12]
Is this compatible with this version of the database?
http://dev.maxmind.com/geoip/geoip2/geolite2/

I tried to do drop-in replacement and got this error

````
throw new Error('Unable to find database info');
          ^
Error: Unable to find database info
    at new module.exports (node_modules/maxmind/lib/database_info.js:131:11)
    at Database.init (node_modules/maxmind/lib/database.js:39:15)
    at new Database (node_modules/maxmind/lib/database.js:25:8)
    at Object.module.exports.init (node_modules/maxmind/lib/lookup_service.js:61:15)
    at Object.<anonymous> (index.js:8:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
````

Do you know how much effort this is? Maybe I can patch it.

Thanks

**Comment by zj8487** [comment]
+1

**Comment by willin** [comment]
+1

**Comment by galkatzburg** [comment]
+1

**Comment by pajtai** [comment]
:+1:

**Comment by jrdi** [comment]
@runk are you planning to include mmdb support soon?

**Comment by runk** [comment]
Looks like it's something I should plan. A lot of people asking. Probably will try to start working on it this week.

**Comment by yonib05** [comment]
+1

**Comment by shaharmor** [comment]
+1

**Comment by YOMorales** [comment]
Thanks, runk. I also need mmdb support as I have the commercial versions of the databases.

**Comment by rogovdm** [comment]
+1

Maybe any changes?

**Comment by gergely-ujvari** [comment]
+1

**Comment by NawarA** [comment]
mmdb support would make this hands down the best library for node. Without mmdb support, its missing a core feature that prevents my team from using this in production. plus i think lack of mmdb support is why this library isnt listed on maxmind's site (the rest of the libraries support mmdb). This one feature would have so many wins.

+1

**Comment by runk** [comment]
Hey guys, I'm working on it. 

Strugling to find time, but looking forward to get it done asap.

**Comment by msimerson** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=8485807)](https://www.bountysource.com/issues/8485807-compatibility-with-geoiplite2-database?utm_source=8485807&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by mathewmeconry** [comment]
+1

**Comment by runk** [comment]
Hey all, pleased to announce that v1.0.0 is released last night, you're more than welcome to give it a go.
