### ISSUE TITLE
Breaking changes in minor version for typings

### ISSUE THREAD

**Issue by SimonSchick** [runk/node-maxmind#125]
Hey, I noticed my build failing after I updated this package to 2.9.

It would be great if you only released major versions when breaking changes were introduced.

I also noticed you started prefixing all interfaces with `I`, please see https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names
The TS team strongly suggests that you don't do that.

**Comment by SimonSchick** [comment]
Nvm it seems that TS silently switched from `@types/maxmind` to yours, not exactly your fault but still a breaking change for TS users.

Please consider creating a PR to delete the DT typings: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by kevcenteno** [comment]
@geoffreak

**Comment by runk** [comment]
No worries @SimonSchick - I'll craft a PR to remove `@types/maxmind` 👍
