### ISSUE TITLE
Open the MMBD File Once

### ISSUE THREAD

**Issue by davewelsh** [runk/node-maxmind#132]
Just a question:

Would it be safe to do something like this:

    let reader;
    maxmind.open(dbFile, (err, r) => {
      if (err) { throw err; }
      reader = r;
    }

    router.get('/ip', requestIp.mw(), (req, res) => {
      if (reader) {
        const response = reader.get(req.clientIp);
        res.send(response);
      } else {
        res.status(500).send('reader not open');
      }
    });

I figure I could shave a lot of time off my Express requests if I don't have to open the mmdb file with each request.

**Comment by knoxcard** [comment]
If this answer works for you or not, let me know!  Please close ticket, if all is good.

**Comment by davewelsh** [comment]
Thanks! Looks like a good solution.
