### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by villanus** [runk/node-maxmind#14]
It would be great if there were a REST api which would allow for other apps (javascript, php, asp.net) to access the Geo IP data. 

A great example is this project:
http://freegeoip.net/
which has a very simple REST api.

Also, 
Would love to have a step by step tutorial on how to deploy the application on something like Heroku.   As an ASP developer, Node.js is still something I have not played with.  I am sure that other developers not familiar with Node.js could greatly benefit from such a step by step guide on getting this installed on something like Herorku for free, and then use an api from the languages they already know.

THANKS IN ADVANCE

**Comment by msimerson** [comment]
I'd vote to close this with a "nah, not worth bothering."  For casual users, they can use [freegeoip.net](http://freegeoip.net/) for free, and if they need more than 10,000 queries per hour, they can deploy their only [copy of the source](https://github.com/fiorix/freegeoip).

It's not hard whip out an Express based API that adds a few API endpoints and serves the GeoIP data via AJAX. But shouldn't such a project be it's own project that depends on this one?

**Comment by runk** [comment]
Yeah, same opinion probably. Closing.
