### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by knoxcard** [runk/node-maxmind#150]
What about using Redis and caching the maxmind API only once so many apps can use it?  Perhaps resulting in even faster lookup times as well.

https://redislabs.com/ebook/part-2-core-concepts/chapter-5-using-redis-for-application-support/5-3-ip-to-city-and-country-lookup/5-3-1-loading-the-location-tables/

**Comment by runk** [comment]
It won't help with performance here. Networks trips are quite costly and cannot be compared with in-memory cache. I can propose extracting geo lookup into its own tiny microservice that doesn't affect rest of your stack.
