### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by wesrice** [runk/node-maxmind#152]
I just wanted to give a heads up that `tiny-lru@>=2` requires Node 8. I realize `node-maxmind` has engine constraints in its `package.json`, but `npm install` does not fail when these constraints are not met, resulting in a passing build in Travis. In the project that I'm currently working on, we utilize `yarn install`, which does fail if any dependency results in a Node version violation. [Here is the build failure](https://travis-ci.com/maxmind/GeoIP2-node/jobs/169327860).

We have decided to drop Node v6 support, so this is no longer an issue for us, but I wanted to alert you in case it is an issue for others.

**Comment by runk** [comment]
Ouch, thanks for the heads up! I'll send a PR to tiny-lru and try to make engine requirements less aggressive.
