### ISSUE TITLE
No support for LTS Node versions

### ISSUE THREAD

**Issue by StarpTech** [runk/node-maxmind#184]
Hi,
the library looks really promising but most of the people can't use them because it doesn't support LTS versions of Node.js e.g 8.x. https://nodejs.org/en/about/releases/ Would you like to support?

**Comment by kevcenteno** [comment]
The [official MaxMind library](https://github.com/maxmind/GeoIP2-node) (which uses an older version of node-maxmind) does provide on-going LTS support.
