### ISSUE TITLE
No sync API?

### ISSUE THREAD

**Issue by MartinKolarik** [runk/node-maxmind#185]
It appears the latest major version completely removed the synchronous `openSync()` method. While moving from callbacks to Promises was definitely a good idea, the lack of a sync version results in a very awkward code in many cases because `await` can't be used in the top level scope:

```js
const maxmind = require('maxmind');
const lookup = await maxmind.open('db.mmdb', options); // not possible, needs to be inside async function
lookup.get('1.2.3.4');
```

Our typical use case of this library looks like this:

```js
const maxmind = require('maxmind');
const lookup = maxmind.openSync('db.mmdb', options);

class C {
    someMethod (ip) {
        ...
        lookup.get();
        ...
    }
}

module.exports = C;

```

Because the DB cannot be opened at the beginning of the file anymore, and the operation is async, any code in the application using the `lookup()` function needs to be async as well or needs to get a DB from the callee.

I think adding the support for sync open back should be fairly easy and it would greatly improve the usability of this package in many cases. What do you think? Is there a specific reason why it was removed?

**Comment by kevcenteno** [comment]
In lieu of `openSync()`, you can use the Reader class directly: https://github.com/runk/node-maxmind/blob/master/src/reader.ts  Basic usage here: https://github.com/runk/node-maxmind/blob/master/src/reader.test.ts#L13

**Comment by MartinKolarik** [comment]
Oh, `Reader` is actually mentioned in the readme in the Typescript section - I did miss that. I suppose the lack of `openSync` isn't that big of a problem then, just the readme could be improved a bit to make this more obvious. Thanks!

**Comment by MartinKolarik** [comment]
@silverwind as @kevcenteno pointed out, there's a very easy workaround:

```js
const MaxMindReader = require('maxmind').Reader;
const lookup = new MaxMindReader(fs.readFileSync(file));
```

I still think it makes sense to add `openSync()` though, so keeping this issue open.

**Comment by silverwind** [comment]
That works, thanks. I still feel there should be a `openSync` again. I too missed the existance of `Reader` because if was only documented in the TypeScript section of the `README` which I blissfully ignored while visually scanning over the document.

**Comment by botaniQQQ** [comment]
@MartinKolarik How to use `cache` param?

```
cache: {
    max: 1000,
    maxAge: 1000000
}
```

**Comment by runk** [comment]
As a second parameter. I might have to add type defs for options.
