### ISSUE TITLE
maxmind.validate is not a function

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [runk/node-maxmind#191]
thanks for the package, I am getting this error when I try to validate ipaddress.
can you please help

**Comment by TheClonker** [comment]
Hey @sowmiyaseshadriii, i just faced the same Problem, if its still an issue for you use:

`const maxmind = require('maxmind');
...
if ( maxmind.default.validate(ip) ) {
 console.log('Valid IP');
}
`

**Comment by runk** [comment]
Fixed in maxmind@3.0.5
