### ISSUE TITLE
Today's releases are empty on NPM

### ISSUE THREAD

**Issue by ben-turner** [runk/node-maxmind#197]
Versions 3.1.0 and 3.1.1 contain no javascript files in NPM. Running `npm install maxmind` creates a directory in node_modules which contains only `LICENSE`, `package.json`, and `README.md`. Installing 3.0.5 fixes the issue as it includes the `lib` directory.

**Comment by fuzzysaj** [comment]
Was about to report this. I thought something was wrong with npm locally for a while.  I'm sure somebody will fix this Monday.  Thanks for the great tool BTW.

**Comment by piotrblasiak** [comment]
Yup. Doesn´t work.

**Comment by sharper** [comment]
Doesn't Work.

**Comment by type11error** [comment]
I'm having trouble with this as well....looks like 3.0.5 is broken as well...

**Comment by jasonswearingen** [comment]
@type11error  ```3.0.5``` works for me.   make sure you are installing the exact match and your lockfile isn't overriding your choice.   

for example, run:

```yarn add maxmind@3.0.5```

**Comment by jasonswearingen** [comment]
pinging @runk in case he's not aware (node-maxmind is broken)

**Comment by runk** [comment]
Fixed via https://github.com/runk/node-maxmind/pull/198

Apologies for the mess up 🙇
