### ISSUE TITLE
Getting prefix length or network associated with record

### ISSUE THREAD

**Issue by oschwald** [runk/node-maxmind#216]
I'd like to add the ability to get the prefix length or network associated with a record to this library. Is this something you might accept a PR for? In terms of API design, do you have any thoughts on what you would prefer it to look like?

For the Go reader, I [added a new `LookupNetwork` method](https://github.com/oschwald/maxminddb-golang/commit/f3bf31c07a7e890d676a25c45020c7bab7f296f2) that returns both the record and the CIDR representation for the associated network.

This would require modifying `findAddressInTree` to return `i`. I see that method is marked public, but I don't see it mentioned in the documentation. Would it be ok to make such a change?

Also, if the new method were to return the CIDR representation rather than just the prefix length, I would need to calculate the first IP of the network. Assuming none of the libraries that are currently in use do this, would it be ok to pull in an additional dependency for it?

**Comment by runk** [comment]
I do not mind this feature, however I'd prefer to have it special method that also returns the mask. 

Re `findAddressInTree` - perhaps we should make it private!
