### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by vithmel** [runk/node-maxmind#232]
Нi, I have some questions about performance:
When synchronous mode is used, the entire database is read into RAM.
1. Do I understand correctly? And every call to` lookup.get()` accesses RAM not the file system?
2. In asynchronous mode, is the database also read into RAM?

**Comment by runk** [comment]
It is correct. Today the only difference in async/sync is at initialisation stage - when database is loaded into memory from filesystem or by other means.
