### ISSUE TITLE
open just once

### ISSUE THREAD

**Issue by measwel** [runk/node-maxmind#235]
I am running my nodejs application in cluster mode. How do I make sure that maxmind db is read only once into memory, but can be used by all spawned nodejs processes? Currently each process is reading its own copy of maxmind, filling up the memory.

**Comment by runk** [comment]
There're no nice ways of dealing with it currently. I'd suggest spinning another api (microservice?) that's doing geo lookup only, and runs 1 process max.

I've been experimenting with shared memory but complexity and performance degradation didn't seem to out-weight the benefits.

**Comment by measwel** [comment]
I thought so. But as I do location lookups on each request, I think calling another service would introduce quite some latency would it not? I would have to wait for the reply before I can continue processing the request in my express server. 

I thought about doing the lookup by the nginx proxy and pass it in a header, but the module for it uses old maxmind dbs. I was unable to compile a module that would use the newer maxmind db's.

**Comment by runk** [comment]
Yeah, you might do it via nginx as well, good option.

How precise you need the lookup to be? City level or country level? Just checking if you can use smaller db to minimise memory footprint

**Comment by measwel** [comment]
city level. The bad thing is that the node module that I have can't read the new maxmind format. It only reads the older legacy db format and those seem outdated and in some cases produce no location.

**Comment by runk** [comment]
Yeah, https://github.com/runk/node-maxmind/tree/v0.6.0 version that worked with legacy format could be used for that (see options), however new one doesn't have this ability (yet?).
