### ISSUE TITLE
Unhandled rejection when watching for updates

### ISSUE THREAD

**Issue by jwest23** [runk/node-maxmind#238]
I'm sporadically getting unhandled promise rejections in a long-lived service which uses the `watchForUpdates` option in `open`.  These occur during database replacement:

 `UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.../node_modules/geolite2/dbs/GeoLite2-City.mmdb'`

A contrived example that demonstrates the problem is:

```javascript
'use strict';

const fs = require('fs');
const geolite2 = require('geolite2');
const maxmind = require('maxmind');
const util = require('util');
const unlink = util.promisify(fs.unlink);

Promise.resolve().then(async () => {

  const lookup = await maxmind.open(geolite2.paths.city, {
    watchForUpdates: true
  });

  await unlink(geolite2.paths.city); // demonstration only

});
```

I imagine changing my database replacement process could work around this, assuming the process works correctly.  The caught error could be passed as the first parameter to the `watchForUpdatesHook`, if provided.

Thanks!

**Comment by runk** [comment]
I think I saw the exact issue recently. Will try to fix it/
