### ISSUE TITLE
Support UTF-8

### ISSUE THREAD

**Issue by Jokero** [runk/node-maxmind#25]
I created module to convert ipgeobase.ru DB to GeoLiteCity format (https://www.npmjs.com/package/geodbconverter). So now I can use node-maxmind to get information about city from ipgeobase. But city and region names are not in UTF-8: 

```javascript
{ countryCode: 'RU',
  countryName: 'Russian Federation',
  region: 'Ð¡Ð°Ð½ÐºÑ-ÐÐµÑÐµÑÐ±ÑÑÐ³',
  city: 'Ð¡Ð°Ð½ÐºÑ-ÐÐµÑÐµÑÐ±ÑÑÐ³',
  postalCode: null,
  latitude: 59.93899999999999,
  longitude: 30.315799999999996,
  dmaCode: 0,
  areaCode: 0,
  metroCode: 0,
  distance: [Function],
  continentCode: 'EU',
  regionName: null }
```

**Comment by Jokero** [comment]
I think getLocation() also should return locId

**Comment by runk** [comment]
Hey there. Original maxmind's database uses single multibyte encoding for strings.

If I'd change it in order to support utf8, I'd break some other stuff. :)

**Comment by runk** [comment]
what is `locId`?

**Comment by Jokero** [comment]
Location id (city id)

**Comment by runk** [comment]
Are you sure it's a part of a record of binary database format?

**Comment by Jokero** [comment]
Unfortunately, there is no `locId` in binary :(
