### ISSUE TITLE
metroCode and dmaCode always return 0

### ISSUE THREAD

**Issue by ben-liang** [runk/node-maxmind#26]
Using the most recent paid "legacy" [GeoIPCity DAT binary](https://download.maxmind.com/app/geoip_download?edition_id=133&date=20150224&suffix=tar.gz), every IP address I look up using `maxmind.getLocation` method returns a `metroCode = 0` and `dmaCode = 0`.

I've stepped through `/lib/lookup/location.js` a couple of times to try to identify the problem, and the issue seems to happen in lines 122-135: 
```js
  if (db.type === DatabaseInfo.CITY_EDITION_REV1) {
    // get DMA code
    var metroareaCombo = 0;
    if (record.countryCode === 'US') {
      recordBufOffset += 3;

      metroareaCombo += recordBuf.readUInt8(recordBufOffset + 0) << (0 * 8) +
        recordBuf.readUInt8(recordBufOffset + 1) << (1 * 8) +
        recordBuf.readUInt8(recordBufOffset + 2) << (2 * 8);

      record.metroCode = record.dmaCode = metroareaCombo / 1000;
      record.areaCode = metroareaCombo % 1000;
    }
  }
```
In this block, `metroareaCombo` never seems to increment properly, and therefore `metroCode`, `dmaCode` and `areaCode` always stay at 0. I've verified that the db.type is correct and that this block is indeed being entered.

**Comment by runk** [comment]
Oh, crap. You're right.

I think I managed to fix that issue in v0.5.4, can you check please?

FYI https://github.com/runk/node-maxmind/commit/078e63f7e9d470f7c4a1e4a5db966a78246d7fd1

**Comment by ben-liang** [comment]
Yep, works now.  Thanks for this!

**Comment by runk** [comment]
Thanks for feedback :+1:
