### ISSUE TITLE
Cannot import named exports

### ISSUE THREAD

**Issue by mdawar** [runk/node-maxmind#267]
Hi, I'm using this package with Node.js version **13.7.0** which has ES modules support enabled by default, I'm trying to import the `Reader` class using:
```javascript
import { Reader } from 'maxmind';
```
Which is causing:
```console
import { Reader } from 'maxmind';
         ^^^^^^
SyntaxError: The requested module 'maxmind' does not provide an export named 'Reader'
```
The `Reader` class is [exported](https://github.com/runk/node-maxmind/blob/557fb57b006206d499a2896bb9464c3f747b42d1/src/index.ts#L78) in the `index.ts` file:
```javascript
export { default as Reader } from './reader';
```

And in the generated `index.js` we can find:
```javascript
var reader_2 = require("./reader");
exports.Reader = reader_2.default;
```

Using the default import works as intended:
```javascript
import maxmind from 'maxmind';
```

I don't know much about TypeScript to provide a fix, so that's why I've opened this issue.

Thank you.

**Comment by runk** [comment]
Hm. Are you trying to load *.ts files in node or something?

**Comment by mdawar** [comment]
@runk I'm not doing anything special, you can reproduce what I'm doing:
```bash
npm init -y
npm i maxmind
```
Then add `"type": "module"` to the`package.json` file, and create a new `index.js` with:
```javascript
import { Reader } from 'maxmind';
```
When running this file `node index.js` you'll get this error that `maxmind` doesn't provide this named export.

**Comment by runk** [comment]
Thanks for explanation! I'll try to repicate it

**Comment by runk** [comment]
I believe it's fixed in latest version of the lib
