### ISSUE TITLE
Watch for updates - leaks

### ISSUE THREAD

**Issue by gjovanov** [runk/node-maxmind#275]
Hi there,
it seem that watch for updates accumulates ever more and more handlers.

For example this:

```javascript
const db = await maxmind.open(mmdbPath, {
      watchForUpdates: true,
      watchForUpdatesHook: () => {
        console.log('MMDB update')
      }
    })
```

First time it outputs 3x `MMDB update`:
Second time it outpus 6x 'MMDB update'
Third time 9x 'MMDB update' and so on...

Do you know why:
1. The first time it outputs 3x logs
2. On every consecutive call, it aggregates the watchForUpdatesHook calls?

Thanks.

**Comment by runk** [comment]
Tried to reproduce it locally with 

```
const maxmind = require('./lib');

(async () => {
  const db = await maxmind.open('./GeoIP2-City-Test.mmdb', {
    watchForUpdates: true,
    watchForUpdatesHook: () => {
      console.log('MMDB update');
    },
  });
})();

```

Changing permissions on the data file for the test, all messaging is as expected. How the data files change in your setup?

**Comment by gjovanov** [comment]
Sorry for the delayed response @runk .

It's seems that related to my level of ignorance. I was running it with the npm script that starts pm2 cluster, hence it was logging it multiple times. So it's not a real issue, but every worker process was outputing the file update.

Sorry for the inconveniece.

Closing...
