### ISSUE TITLE
IPv6 to IPv4

### ISSUE THREAD

**Issue by DonRichards** [runk/node-maxmind#28]
Trying to pass the client's IP to Maxmind to resolve the state(Fl, GA, CA, etc) but I get IPv6. When I manually set client_IP_address to a static IPv4 it worked correctly. Any idea how to convert this IPv6 to IPv4 or get Maxmind to accept a IPv6 address? 

## Here is the code
> var client_IP_address = req.connection.remoteAddress;
> var ipAddress_state = maxmind.getLocation(client_IP_address);
> console.log(client_IP_address + ipAddress_state);

## Console log out
> ::ffff:132.170.200.83 null

**Comment by runk** [comment]
@DonRichards, if you want to lookup ipv6 addresses you need to load a ipv6 database and start using `getLocationV6` method.

I should mention that it would be nice to have a nice error message about invalid ipv4 format (you're supplying v6, right). But this sort of validation is quite expensive and I really want to avoid any performance degradation. 

Hope it helps.

**Comment by DonRichards** [comment]
True, thanks for the help. I didn't want to use IPv6 but Node.js just switched the default to IPv6.
