### ISSUE TITLE
Shouldn't this be async?

### ISSUE THREAD

**Issue by CamiloMM** [runk/node-maxmind#30]
In node.js, unlike PHP, everything is event-based and there's a single event loop for the entire app; which scales pretty well and can handle a lot more concurrency.

However, as soon as you start doing heavy things synchronously... it doesn't scale that well anymore. Reading a DB file seems like such a scenario.

Actually, this whole anti-IO-bound philosophy is so ingrained in Node, I might be mistaken and this is just fine, but, isn't there a design problem here? Shouldn't the API for this module have async methods and encourage them over the sync ones?

Maybe this is only the case with no cache or `indexCache`, which I was planning on using since it seems the best trade-off.

(of course, the sync methods are by far nicer to use, but that's why I want to know if they're not going to choke under load spikes).

**Comment by CamiloMM** [comment]
By the way: [`maxmind-db-reader`](https://github.com/PaddeK/node-maxmind-db) allows for sync and async variants, both for initialization and for DB access. I think this is a great way to do it.

**Comment by runk** [comment]
To be honest I'm not really convinced about async methods in case with this particular library. 

You're totally right saying that it's much easier to use sync methods. Also, lookups took expected fixed time, so you can be pretty confident about your app performance. I recommend to enable cache, it's only 50 megs for full city level database. Considering memory prices it's really good tradeoff between performance and cost. Another reason why it was done in sync fashion is that built-in `fs` modules has sync interface.

This lib was built with particular focus on performance and I guess at this stage this is a top performing maxmind lib available for nodejs. Please correct me if I'm wrong and I attempt to make it faster than competitors :) This lib used in systems that handle 20,000-25,000 requests a second and it works pretty well.

I'd love to see some real benchmark for a our use case. I have some doubts that async version would be a bit slower. :smile_cat:
