### ISSUE TITLE
Improper Typescript Definitions

### ISSUE THREAD

**Issue by nolawnchairs** [runk/node-maxmind#364]
The definitions for the City result contains a union type with empty objects that conflict with VSCode intellisense. Note that I'm using the City object as the example, but I see this same issue with other model type definitions::

```typescript
export default class City extends Country {
    readonly city: records.CityRecord | {};
    readonly location: records.LocationRecord | {};
    readonly postal: records.PostalRecord | {};
    readonly subdivisions: records.SubdivisionsRecord[] | [];
    constructor(response: CityResponse);
}
```

As you can see, when trying to use the resultant reader value, the editor shows the following errors:

![Screenshot from 2020-10-15 14-53-11](https://user-images.githubusercontent.com/224439/96093439-55d99a80-0ef6-11eb-84c4-30c0de82a986.png)

This is because the TS engine assumes the lowest-possible denominator of a union type, so it assumes the empty object `{}` instead of `CountryRecord`. The only way around this is to cast the object to a type or interface that removes the union types:

```typescript
import { Reader, CountryRecord, SubdivisionsRecord, CityRecord, PostalRecord, LocationRecord, TraitsRecord } from '@maxmind/geoip2-node'
import ReaderModel from '@maxmind/geoip2-node/dist/src/readerModel'

interface GeoIpResult {
  country: CountryRecord,
  subdivisions: SubdivisionsRecord[],
  city: CityRecord,
  postal: PostalRecord,
  location: LocationRecord,
  traits: TraitsRecord
}

const { country, subdivisions, city, postal, location, traits } = reader.city(ip) as GeoIpResult
```
This allows for normal usage, but is a completely unnecessary step. I should also note that `ReaderModel` should be exported (defined) in your main index module, so importing from `@maxmind/geoip2-node/dist/src/readerModel` would not become necessary.

There is also an error with the `SubdivisionsRecord` array, as it's defined. 
```typescript
readonly subdivisions: records.SubdivisionsRecord[] | [];
```

There is no need to union with an empty array type, as this will hint to the compiler that's an empty array of nothing as opposed to an empty array of `SubdivisionsRecord`. All this serves to do is erase the type hints for the resultant array. If you're returning an empty array, it can remain the type of the expected array, since it won't be iterated anyways.

```typescript
readonly subdivisions: records.SubdivisionsRecord[]
```

It would be better to remove this union type all together and do one of the following, assuming that one of these record sets would not contain a result:
1) Make all properties of nullable types

```typescript
export interface CityRecord {
    readonly confidence?: number;
    readonly geonameId?: number;
    readonly names?: Names;
}
```

2) Make the record itself nullable and return null or undefined if it does not exist, instead of an empty object
```typescript
export default class City extends Country {
    readonly city?: records.CityRecord;
    readonly location?: records.LocationRecord;
    readonly postal?: records.PostalRecord;
    readonly subdivisions?: records.SubdivisionsRecord[];
    constructor(response: CityResponse);
}
```

The latter of course, would introduce breaking changes but would conform more to JavaScript/NodeJS conventions.

**Comment by runk** [comment]
Hi, not sure you're reporting to proper module maintainer. All `@maxmind/*` modules are owned and managed by Maxmind itself, current repo is not official. In your examples you're referring to official one, whilst this repo maintains module named `maxmind`. 

Indeed it is confusing cannot disagree.
