### ISSUE TITLE
Difference with mmdb-lib

### ISSUE THREAD

**Issue by gonzus** [runk/node-maxmind#427]
What is the difference between this module and https://github.com/runk/mmdb-lib? They have a very similar interface, and both were created by the same author, correct? Which one should I use?

**Comment by runk** [comment]
Hey @gonzus 👋  `mmdb-lib` is used under the bonnet in current repo - `maxmind`. 

The library provides simple tools for working with the databased in mmdb format, however it doesn't solve problem of how you load the database, how you do refreshes/watch for changes - basically things that are specific for nodejs environment. 

E.g. library can be used in browser as well, as long you managed to download (or embed?) database somehow.
