### ISSUE TITLE
How to get city name?

### ISSUE THREAD

**Issue by jainsourabh2** [runk/node-maxmind#44]
I am not able to get the city name. The returned object only has continent , country , location and registered_country object.

**Comment by runk** [comment]
What sort of database you use?

**Comment by jainsourabh2** [comment]
I downloaded the mmdb database from the below link:

http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz

I was testing it for a few IP addresses before using it in my code but it doesn't have any city information.

**Comment by runk** [comment]
Can you please share the code snippet you use?

**Comment by jainsourabh2** [comment]
var maxmind = require('maxmind');

var cityLookup = maxmind.open('./GeoDB/GeoLite2-City.mmdb');
var city = cityLookup.get('121.242.84.10');

console.log(city);


This is the output

{ continent:
   { code: 'AS',
     geoname_id: 6255147,
     names:
      { de: 'Asien',
        en: 'Asia',
        es: 'Asia',
        fr: 'Asie',
        ja: 'アジア',
        'pt-BR': 'Ásia',
        ru: 'Азия',
        'zh-CN': '亚洲' } },
  country:
   { geoname_id: 1269750,
     iso_code: 'IN',
     names:
      { de: 'Indien',
        en: 'India',
        es: 'India',
        fr: 'Inde',
        ja: 'インド',
        'pt-BR': 'Índia',
        ru: 'Индия',
        'zh-CN': '印度' } },
  location:
   { accuracy_radius: 1000,
     latitude: 20,
     longitude: 77,
     time_zone: 'Asia/Kolkata' },
  registered_country:
   { geoname_id: 1269750,
     iso_code: 'IN',
     names:
      { de: 'Indien',
        en: 'India',
        es: 'India',
        fr: 'Inde',
        ja: 'インド',
        'pt-BR': 'Índia',
        ru: 'Индия',
        'zh-CN': '印度' } } }


This is output from maxmind website:

IP Address	Location
121.242.84.10	Thane,Maharashtra,India,Asia

**Comment by runk** [comment]
The reason you aren't getting city name is because "GeoLite" databases are free and not very accurate. I'm sure that Maxmind uses a full version of its database for demos on their website.
