### ISSUE TITLE
Regression: watchForUpdates

### ISSUE THREAD

**Issue by Nicholi** [runk/node-maxmind#444]
It seems a regression occurred between release 4.2.0 and 4.3.0 when using `watchForUpdates`. The updated Reader object never gets to calling application.

Specifically this commit: https://github.com/runk/node-maxmind/commit/817cfceefc15ba265eef30169b77263246d9827c#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

Instead of reloading the already returned Reader object, we are now creating an entirely new Reader. However the new reader is never emitted to anyone, so is anything ever updated?

I assume the `load()` functionality is intended to get added to mmdb-lib, just as the older reader.ts before it?
Or the new Reader object could be emitted in watchForUpdatesHook, letting calling application handle updating any references?

For now downgrading to 4.2.0 is simple workaround.

**Comment by runk** [comment]
Oh, yeah I see what you mean. Clearly a bug 😞

**Comment by runk** [comment]
Adding this in mmdb lib first: https://github.com/runk/mmdb-lib/pull/7

**Comment by runk** [comment]
Thanks for report @Nicholi 🙇
