### ISSUE TITLE
Publish new version to npm?

### ISSUE THREAD

**Issue by pdehaan** [runk/node-maxmind#45]
Currently when installing from npm, you get the following warning:

```sh
npm WARN engine maxmind@1.1.0: wanted: {"node":">=0.8.0","npm":"1"} (current: {"node":"4.4.7","npm":"2.15.8"})
```

It looks like this is fixed in latest master (see [https://github.com/runk/node-maxmind/commit/f7aa9314acb68a512437ffb85b784592c6af7040#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45](https://github.com/runk/node-maxmind/commit/f7aa9314acb68a512437ffb85b784592c6af7040#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45)):

```js
  "engines": {
    "node": ">=0.8.0",
    "npm": ">=1"
  },
```

Would it be possible to get a **maxmind@1.1.1** published to npm to silence the **npm@1** warning?

**Comment by runk** [comment]
Done! https://www.npmjs.com/package/maxmind

**Comment by pdehaan** [comment]
🍻 Thanks @runk!
