### ISSUE TITLE
Read db file asynchronously

### ISSUE THREAD

**Issue by palamccc** [runk/node-maxmind#48]
Unzipped coutry database size is 8Mb and Unzipped city database size is 63Mb, commercial database may be even bigger. loading this big file by readFileSync is not recommended. 

https://github.com/runk/node-maxmind/blob/e25bdb2e66e2ee0ea213121b420d09754424331c/lib/reader.js#L23

I request to add async open api, with callback. so errors can be handled in node.js style.  I can provide pull request, if you are interested in this change.

**Comment by runk** [comment]
You're right, I'll make this change.

**Comment by runk** [comment]
Has been done.
