### ISSUE TITLE
How to use default maxmind gzip file?

### ISSUE THREAD

**Issue by YoloTEAM** [runk/node-maxmind#61]
I'm downloaded mmdb file as gzip compression.

How to use with gzip file for smaller file store, save my storage.

Just decompress .gz (~29MB) to .mmdb (~49MB) and work well with example code and stuck at .gz file

`var GeoLite2_City = maxmind.openSync('./db/GeoLite2-City.mmdb.gz');`

Please give me suggestions for good way to solve this. Thanks you.

**Comment by runk** [comment]
Hey - you have to use .mmdb extension, gzip isn't supported.

**Comment by YoloTEAM** [comment]
Ok, many thanks :smile:
