### ISSUE TITLE
Add support for response schemas/templates

### ISSUE THREAD

**Issue by 0xMANFRE** [runk/node-maxmind#612]
Hi, thanks for the package, I'm using it for my backend.
There is a problem that I'm facing though. I want to get complete responses, by that I mean that fields which are not present in the database are also not returned in the response.
Is it possible to get all the JSON fields, and give the empty one a value of null or empty string?
Example (using a GitHub IP):
```json
{
	"city": {
		"geoname_id": 2925533,
		"names": {
			"de": "Frankfurt am Main",
			"en": "Frankfurt am Main",
			"es": "Francfort",
			"fr": "Francfort-sur-le-Main",
			"ja": "フランクフルト・アム・マイン",
			"pt-BR": "Frankfurt am Main",
			"ru": "Франкфурт",
			"zh-CN": "法兰克福"
		}
	},
	"continent": {
		"code": "EU",
		"geoname_id": 6255148,
		"names": {
			"de": "Europa",
			"en": "Europe",
			"es": "Europa",
			"fr": "Europe",
			"ja": "ヨーロッパ",
			"pt-BR": "Europa",
			"ru": "Европа",
			"zh-CN": "欧洲"
		}
	},
	"country": {
		"geoname_id": 2921044,
		"is_in_european_union": true,
		"iso_code": "DE",
		"names": {
			"de": "Deutschland",
			"en": "Germany",
			"es": "Alemania",
			"fr": "Allemagne",
			"ja": "ドイツ連邦共和国",
			"pt-BR": "Alemanha",
			"ru": "ФРГ",
			"zh-CN": "德国"
		}
	},
	"location": {
		"accuracy_radius": 20,
		"latitude": 50.1188,
		"longitude": 8.6843,
		"time_zone": "Europe/Berlin"
	},
	"postal": {
		"code": "60313"
	},
	"registered_country": {
		"geoname_id": 6252001,
		"iso_code": "US",
		"names": {
			"de": "Vereinigte Staaten",
			"en": "United States",
			"es": "Estados Unidos",
			"fr": "États Unis",
			"ja": "アメリカ",
			"pt-BR": "EUA",
			"ru": "США",
			"zh-CN": "美国"
		}
	},
	"subdivisions": [
		{
			"geoname_id": 2905330,
			"iso_code": "HE",
			"names": {
				"de": "Hessen",
				"en": "Hesse",
				"es": "Hessen",
				"fr": "Hesse",
				"ru": "Гессен"
			}
		}
	]
}
```

The `subdivisions[0].names` is missing `ja, pt-BR, zh-CN`. I would like to have those fields returned, and have a empty value like null or empty string.
The same also applies in other fields. If the entire `city` object is missing, having the return values set like this:
```json
	"city": {
		"geoname_id": null,
		"names": {
			"de": null,
			"en": null,
			"es": null,
			"fr": null,
			"ja": null,
			"pt-BR": null,
			"ru": null,
			"zh-CN": null
		}
	},
```

I would also love to have predefined schemas, or even custom ones, so it would return only the fields I need.
Kind of like the [select fields in Prisma ORM](https://www.prisma.io/docs/concepts/components/prisma-client/select-fields#select-specific-fields).

I have coded lot of checks to see if these fields exist, before showing the value. I do not find it as an elegant solution so I'm asking you to consider this feature.

**Comment by runk** [comment]
Hey, thanks for your interest in this module.

Today this module returns data as-is from the binary maxmind databases, without applying any normalisation or sanitisation. I'm struggling to see value in this feature being part of this module's code functionality, however, you're welcome to make a contribution with this feature (leaving it optional and off by default).

This particular use case you are describing very well covered in typescript with optional chaining:

```
const good = a?.b?.c;
// instead of 
const bad = a && a.b && a.b.c;
```

... and it's also available in modern js engines - try it in chrome's console:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by 0xMANFRE** [comment]
> optional chaining

Thanks, I was not aware of this feature. I will use it extensively from now on.

> you're welcome to make a contribution with this feature (leaving it optional and off by default)

Right now I don't have time for this, but I will consider doing it in the future.
