### ISSUE TITLE
Can't get info by ip

### ISSUE THREAD

**Issue by lait1989** [runk/node-maxmind#647]
After update to 4.3.10, i am get an error:

`node_modules/tiny-lru/dist/tiny-lru.cjs:102#012#011#has (key) {#012#011     ^#012#012SyntaxError: Unexpected token '('#012    at wrapSafe (internal/modules/cjs/loader.js:1047:16)#012    at Module._compile (internal/modules/cjs/loader.js:1097:27)#012    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)#012    at Module.load (internal/modules/cjs/loader.js:977:32)#012    at Function.Module._load (internal/modules/cjs/loader.js:877:14)#012    at Module.require (internal/modules/cjs/loader.js:1019:19)#012    at require (internal/modules/cjs/helpers.js:77:18)#012    at Object.<anonymous> (/var/dct/builds/prod-ru-v23.16/node_modules/maxmind/lib/index.js:24:20)#012    at Module._compile (internal/modules/cjs/loader.js:1133:30)#012    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)#012    at Module.load (internal/modules/cjs/loader.js:977:32)#012    at Function.Module._load (internal/modules/cjs/loader.js:877:14)#012    at Module.require (internal/modules/cjs/loader.js:1019:19)#012    at require (internal/modules/cjs/helpers.js:77:18)#012    at Object.<anonymous> (/var/dct/builds/prod-ru-v23.16/node_modules/mangoCore/lib/geoip.js:6:11)#012    at Module._compile (internal/modules/cjs/loader.js:1133:30)`

What i need to fix?

**Comment by runk** [comment]
Likely you're on node@10 or below. This module needs node >= 10, as per [package.json file](https://github.com/runk/node-maxmind/blob/master/package.json#L61)
