### ISSUE TITLE
ipv6 issues

### ISSUE THREAD

**Issue by akayami** [runk/node-maxmind#65]
I've just run into this issue: 
Using node 7.7.3 with express 4.14.1, on AWS, when I call req.ip I get this:
`::ffff:172.31.7.183`

I did some research about this and it seems to be explained here:
http://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1#33790357

I think the library should ideally be able to deal with any notation used, so that a user can just throw the req.ip into the library and get a valid result.

**Comment by runk** [comment]
Erm. Not sure if it's a bug report or not. Module support ipv6 and ipv4 in ipv6 notation, see: https://github.com/runk/node-maxmind/pull/66
