### ISSUE TITLE
connect.multipart() will be removed in connect 3.0 Error after using maxmind in my code

### ISSUE THREAD

**Issue by PrasanthJayaraman** [runk/node-maxmind#67]
I have a node app which running fine for last one year. For a new feature i added maxmind NPM module and used Geo2-city mmdb as mentioned in doc and code level it is working fine.

But suddenly often i'm getting this error.
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0

And my app getting restarted. This happens every 5-20 mins once.

Please give me a solution.

**Comment by runk** [comment]
Hey @PrasanthJayaraman, your issue is not related to maxmind module at all. 

I'd suggest to upgrade to express v4, check https://github.com/felixge/node-formidable for multipart uploads. Cannot advise on limit middleware thought. Try searching on npmjs.org or stackoverflow.

Good luck.
