### ISSUE TITLE
Memory leak in version 4.3.13

### ISSUE THREAD

**Issue by eliottvincent** [runk/node-maxmind#740]
Hey there!

First of all, thanks for your library, we use it in production at Crisp.
Our usage is very simple.

First we initialize maxmind, when the server boots (so, only once):

```js
  __init_geoip() {
    return Promise.resolve()
      .then(() => {
        return maxmind.open(this._app.config.geoip.database);
      })
      .then((geoip) => {
        this.__geoip = geoip;

        return Promise.resolve();
      });
  }
```

Then we have this utility method called `lookup` that does a `.get`:
```js   
  lookup(ip) {
    let _lookup_data = (
      this.__geoip.get(ip) || {}
    );

    return _lookup_data;
  }
```

This method is called around **1M times per day** per server, so around 12 calls per second.

We have recently upgraded maxmind from 4.3.11 to 4.3.13. After a few hours in, we noticed a memory leak on our server:
![Screen Shot 2023-10-03 at 10 02 33@2x](https://github.com/runk/node-maxmind/assets/24720375/0bd41156-bcc0-4626-98f7-15eb87d00562)

We rolled back the maxmind upgrade, and the memory leak was gone after that:
![Screen Shot 2023-10-03 at 10 05 48@2x](https://github.com/runk/node-maxmind/assets/24720375/fed019df-ae77-4c7d-b303-d3d50bdb8d39)

While doing a diff between version 4.3.11 and 4.3.13, the only noticeable change I see is the "tiny-lru" upgrade from 11.0.1 to 11.1.2, so I suspect something changed there!

Node version: 20.5.1
NPM version: 9.8.1

**Comment by runk** [comment]
Thanks for the report, I'm following this up with the tiny-lru maintainers

**Comment by avoidwork** [comment]
Why assume the bug is the tiny-lru and not maxmind itself? The technical difference is a boolean which resets TTL on a record via set() making it possible to use more memory or expose buggy code that blocks cache invalidation. That was called out as a real problem a few times. It's a few lines of code delta between the versions.

**Comment by avoidwork** [comment]
You also have to enable this TTL reset, it's disabled by default.

**Comment by avoidwork** [comment]
There was a regression with tiny-lru at 11.1.2, such that a statement without test coverage was deleted. It was required to balance the tree, without it objects were leaking. It's been fixed in 11.2.1, and a test has been added for re-balancing.

**Comment by runk** [comment]
Thanks @avoidwork 🙇 

@eliottvincent can you try https://github.com/runk/node-maxmind/releases/tag/v4.3.15 - it should have latest tiny-lru

**Comment by oranciog-bd** [comment]
Hy!

We were also impacted by this memory leak. I have updated to v4.3.15 and it seems that the memory remains stable.
Thank you.

**Comment by eliottvincent** [comment]
Upgraded to latest version and everything is all right now! Thanks @runk and @avoidwork
