### ISSUE TITLE
LRU Cache takes more memory, on long running process

### ISSUE THREAD

**Issue by palamccc** [runk/node-maxmind#77]
I'm running maxmind in production for long time with free maxmind city db (50mb file). I found that memory usage increases linearly over time. after some error and trial, we found that lru-cache is the culprit.

In the following test code, we found that,
- With default cache (with 50000 items), process takes about  290mb in RAM and stays constant after
- With small cache (just 10 items), process takes about  97mb in RAM and stays constant after
- With no cache, process takes about 85mb in RAM and stays constant after

lru-cache is configured to default 50,000 items max. But it takes 200mb in RAM, which looks very big to me. we are already loading mmdb file in RAM, which itself takes 50mb to 100mb. and on top of that 200mb is big.  I recommend you to reduce to some more reasonable number.

I've added option to disable cache completely, and sent that as pull request. Its a non breaking change. changing default value, may break existing users.

```js
const maxmind = require('maxmind');

const printMem = () => console.log(`${Math.round(process.memoryUsage().rss / (1024 * 1024))} mb`);
const num = () => Math.floor(Math.random() * 255);
const checkRandomIP = db => db.get(`${num()}.${num()}.${num()}.${num()}`);

// no cache
const opts = { cache: false };

// default cache
// const opts = {};

// very small cache
// const opts = { cache: { max: 10 } };

maxmind.open('GeoLite2-City.mmdb', opts, (err, db) => setInterval(checkRandomIP, 1, db));
setInterval(printMem, 5000);
```

**Comment by nivaldodasilva** [comment]
Any solution for this problem?

**Comment by runk** [comment]
There's linked PR as you can see - #78. Tests failing, would be nice if someone get it fixed before merge.

**Comment by runk** [comment]
While it's pending it can suggest tweaking cache settings, let's say set max items to 500 or something similar.

**Comment by runk** [comment]
I reworked cache a bit, now default cache size is only 6000 (used to be 50000). Like pointed before, I suggest setting size to small number to mitigate memory issue.

**Comment by runk** [comment]
Closing for now.
