### ISSUE TITLE
Fail with an explicit message when .get() is called with a non string input

### ISSUE THREAD

**Issue by oliviertassinari** [runk/node-maxmind#81]
I have noticed the following error when the `.get(input)` method is called with a non string input.

> TypeError: Cannot read property 'indexOf' of undefined
     at Object.exports.parse (/app/node_modules/maxmind/lib/ip.js:65:14)
     at Reader.findAddressInTree (/app/node_modules/maxmind/lib/reader.js:58:27)
     at Reader.get (/app/node_modules/maxmind/lib/reader.js:52:22)

I do think you have the opportunity to make the development experience better with an explicit failing message.

**Comment by runk** [comment]
Not sure it's a high priority. Custom error handling and checking the input will make lib slower, which I don't really like to do.

**Comment by oliviertassinari** [comment]
...

**Comment by runk** [comment]
https://github.com/runk/node-maxmind/blob/master/lib/ip.js#L81
