### ISSUE TITLE
error - (0 , assert_1.default) is not a function

### ISSUE THREAD

**Issue by matiasfour** [runk/node-maxmind#811]
This code:
`const lookup = await maxmind.open<CityResponse>('/opt/app/GeoLite2-City.mmdb');`
is causing this error:

error - ../../node_modules/mmdb-lib/lib/decoder.js (8:0) @ <unknown>
error - (0 , assert_1.default) is not a function

<img width="1094" alt="image" src="https://github.com/runk/node-maxmind/assets/66100432/7886b342-9033-4976-9816-4e254749a27d">

I have maxmind latest version installed.

**Comment by runk** [comment]
Do you attempt to use it in browser?
